kind: "EntandoPlugin"
apiVersion: "entando.org/v1alpha1"
metadata:
  name: "pda-plugin"
spec:
  image: "entando/entando-process-driven-plugin"
  replicas: 1
  dbms: "postgresql"
  roles:
    - name: "task-list"
      code: "task-list"
    - name: "task-get"
      code: "task-get"
    - name: "task-definition-columns-list"
      code: "task-definition-columns-list"
    - name: "task-comments-list"
      code: "task-comments-list"
    - name: "task-comments-get"
      code: "task-comments-get"
    - name: "task-comments-create"
      code: "task-comments-create"
    - name: "task-comments-delete"
      code: "task-comments-delete"
    - name: "task-form-get"
      code: "task-form-get"
    - name: "task-form-submit"
      code: "task-form-submit"
    - name: "connection-list"
      code: "connection-list"
    - name: "connection-get"
      code: "connection-get"
    - name: "connection-create"
      code: "connection-create"
    - name: "connection-edit"
      code: "connection-edit"
    - name: "connection-delete"
      code: "connection-delete"
    - name: "process-definition-list"
      code: "process-definition-list"
    - name: "process-diagram"
      code: "process-diagram"
    - name: "process-definition-form-get"
      code: "process-definition-form-get"
    - name: "process-definition-form-submit"
      code: "process-definition-form-submit"
    - name: "group-list"
      code: "group-list"
    - name: "summary-list"
      code: "summary-list"
    - name: "summary-get"
      code: "summary-get"
  permissions: []
  parameters: {}
  ingressPath: "/pda"
  healthCheckPath: "/actuator/health"
  securityLevel: lenient
  connectionConfigNames: []
